/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazEmpresa;

import gestioninmuebleudc.Edificio;
import gestioninmuebleudc.GestionInmuebleUdc;
import gestioninmuebleudc.Piso;
import gestioninmuebleudc.Local;
import javax.swing.JOptionPane;

/**
 *
 * @author Danyysk
 */
public class AgregarEdificio extends javax.swing.JFrame {
    
    //atributos 
    public static int pisoActual; //para imprimir por cual piso vamos al momento de llenar un edificio de n pisos    
    public static int localActual;
    
    
    public AgregarEdificio() {
        initComponents();
        this.setLocationRelativeTo(null); //fijamos la ventana en la mitad de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        textNombre = new javax.swing.JLabel();
        textDireccion = new javax.swing.JLabel();
        textPisos = new javax.swing.JLabel();
        textPrecio = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        pisos = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        tituloMenu = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        textLocales = new javax.swing.JLabel();
        local = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        textNombre.setText("Nombre Edificio:");

        textDireccion.setText("Direccion Edificio:");

        textPisos.setText("Pisos Edificio:");

        textPrecio.setText("Precio Alquiler del edificio:");

        nombre.setText(" ");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        direccion.setText(" ");

        pisos.setText(" ");
        pisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pisosActionPerformed(evt);
            }
        });

        precio.setText(" ");

        tituloMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tituloMenu.setText("AGREGAR EDIFICIO");

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        textLocales.setText("Locales:");

        local.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloMenu)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textPisos, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textLocales, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nombre)
                                            .addComponent(direccion)
                                            .addComponent(pisos)
                                            .addComponent(precio)
                                            .addComponent(local, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(confirmar)))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(back))
                .addGap(13, 13, 13)
                .addComponent(tituloMenu)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDireccion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPisos)
                    .addComponent(pisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPrecio)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLocales)
                    .addComponent(local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(confirmar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0); //salimos en caso de que presionen exit
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false); //cerramos la ventana actual y volvemos a la anterior
        MenuEmpresa empresa = new MenuEmpresa(); //creamos un objeto
        empresa.setVisible(true); //ahora a ese objeto le cambiamos a true su atribito de visibilidad para que sea visible
    }//GEN-LAST:event_backActionPerformed

    private void pisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pisosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pisosActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        // TODO add your handling code here:
        //aca inicia la verdadera magia
        
        String direccionE = direccion.getText();
        float precioE = Float.parseFloat(precio.getText());
        String nombreE = nombre.getText();
        int pisoE = Integer.parseInt(pisos.getText());
        int localE = Integer.parseInt(local.getText());
                
        //creamos el edificio dentro del array de inmuebles
        GestionInmuebleUdc.listaInmuebles.add(new Edificio(direccionE, precioE)); //añadimos direccion y precio
        
        int aux = 0; //este auxiliar aumentara en 1 con cada iteraccion para asignarle un valor a pisoActual 

        //ahora hacemos un for para iterar la n cantidad de veces que se debe abrir el submenu para agregar piso
        //si se coloco que se tenia 3 pisos se deben crear 3 objetos diferentes de la clase AgregarPisoEdificio
        for(int i = 0; i < pisoE; i++){
            
            AgregarEdificio.pisoActual = aux + 1;
            
            this.setVisible(false); //hacemos invisible la interfaz actual

                //utilizamos esta clase que es un JDialog en lugar de un JFrame
                AgregarPisoEdificio localMenu = new AgregarPisoEdificio(this,true);
                localMenu.setModal(true); //volvemos modal
                localMenu.setVisible(true); //hacemos visible el menu de piso 

            Edificio.agregarPiso(new Piso(direccionE,AgregarPisoEdificio.precioPiso,Piso.numeroPiso,Piso.descripcion));//creamos el piso
            aux++;
        }
        
        JOptionPane.showMessageDialog(null,"Llenado de PISOS compleado","",JOptionPane.INFORMATION_MESSAGE);
        aux = 0;
        
        for(int i = 0; i < localE; i++){
            
            AgregarEdificio.localActual = aux + 1;
            
            this.setVisible(false); //hacemos invisible la interfaz actual
            
            //utilizamos esta clase que es un JDialog en lugar de un JFrame
            AgregarPisoEdificio localMenu = new AgregarPisoEdificio(this,true);
            localMenu.setModal(true); //volvemos modal
            localMenu.setVisible(true); //hacemos visible el menu de piso  

            Edificio.agregarLocal(new Local(direccionE,AgregarPisoEdificio.precioPiso,Piso.descripcion));//creamos el piso
            aux++;
        }
        JOptionPane.showMessageDialog(null,"Llenado de LOCALES compleado","",JOptionPane.INFORMATION_MESSAGE);
        
        //despues de la iteracion volvemos al menu de empresa  
        MenuEmpresa menu = new MenuEmpresa();
        menu.setVisible(true);
    }//GEN-LAST:event_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEdificio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton confirmar;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton exit;
    private javax.swing.JTextField local;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pisos;
    private javax.swing.JTextField precio;
    private javax.swing.JLabel textDireccion;
    private javax.swing.JLabel textLocales;
    private javax.swing.JLabel textNombre;
    private javax.swing.JLabel textPisos;
    private javax.swing.JLabel textPrecio;
    private javax.swing.JLabel tituloMenu;
    // End of variables declaration//GEN-END:variables
}
