/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazEmpresa;

import gestioninmuebleudc.Edificio;
import gestioninmuebleudc.Finca;
import gestioninmuebleudc.GestionInmuebleUdc;
import interfazUsuario.MenuDisponible;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Danyysk
 */
public class AgregarFinca extends javax.swing.JFrame {

    /**
     * Creates new form AgregarPisoEdificio
     */
    
   //AgregarPisoEdificio es diferente de AgregarEdificio puesto que aca no se pide el piso ya que el sistema lo hace automatico
    //en el AgregarPiso si se pide el numero del piso
    public AgregarFinca() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/empresaIcon.png")).getImage());
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        tituloMenu = new javax.swing.JLabel();
        textDescripcion = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        precio = new javax.swing.JTextField();
        textPrecio = new javax.swing.JLabel();
        textDireccion = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        imagenLateral = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        tituloMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tituloMenu.setText("AGREGAR FINCA");
        getContentPane().add(tituloMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        textDescripcion.setText("Descripcion");
        getContentPane().add(textDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        descripcion.setText("Bonita y grande");
        descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionActionPerformed(evt);
            }
        });
        getContentPane().add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 110, -1));

        confirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        precio.setText("500000");
        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 110, -1));

        textPrecio.setText("Precio Alquiler");
        getContentPane().add(textPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        textDireccion.setText("Direccion");
        getContentPane().add(textDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        direccion.setText("salida del pueblo");
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 110, -1));

        imagenLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edificioColorFondo.png"))); // NOI18N
        imagenLateral.setText("jLabel2");
        getContentPane().add(imagenLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        //para retroceder
        
        this.setVisible(false); //ocultamos el menu actual
        MenuEmpresa menu = new MenuEmpresa();
        
        menu.setVisible(true); //hacemos visible el menu anterior
    }//GEN-LAST:event_backActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        //creamos un objeto de la clase Finca que tendra todos estos datos los cuales ya pedimos en la interfaz grafica
        
        //generamos un codigo random para el id
        Random idRandom = new Random();
        
        //con ayuda del auxiliar le asignamos a este random al auxiliar
        //establecemos que queremos que sea entre 0 y 99 y a eso le sumamos 200
        //es decir, nuestro intervalo sera de 200 a 299
        int auxId = 200 + idRandom.nextInt(99);
        
        //tenemos que verificar que el ID del edificio sea unico
        boolean condicion = true;
        for(int i = 0; i < GestionInmuebleUdc.listaInmuebles.size(); i++){
            //comparamos si el id ingresado se encuentra en nuestro arraylist 
            if(auxId == GestionInmuebleUdc.listaInmuebles.get(i).getId()){
                condicion = false; //si se encuentra entonces marcamos como false
            }
        }
        
        //si la condicion no se hizo false, entonces
        if(condicion){
            //a este objeto lo ingresaremos al arraylist de inmuebles
            GestionInmuebleUdc.listaInmuebles.add(new Finca(direccion.getText(), 
                    Float.parseFloat(precio.getText()),descripcion.getText(), -1, auxId));
            
            //esto es para MenuDisponible
            //una clase del package de interfazUsuario, en MenuDisponible se encuentra mas info sobre este proceso
            MenuDisponible.precio4Static = precio.getText();
            MenuDisponible.id4Static = String.valueOf(auxId);
            MenuDisponible.descripcion4Static = descripcion.getText();
        } else {
            JOptionPane.showMessageDialog(null,"El ID que ingreso se encuentra\n" + "ocupado por otro inmueble\nIntente de nuevo","Agregar Finca",JOptionPane.INFORMATION_MESSAGE);
        }
        
        this.setVisible(false); //ocultamos este menu 
        MenuEmpresa menu = new MenuEmpresa(); //volvemos al menu de empresa
        menu.setVisible(true);
    }//GEN-LAST:event_confirmarActionPerformed

    private void descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionActionPerformed

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarFinca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarFinca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarFinca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarFinca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarFinca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton confirmar;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton exit;
    private javax.swing.JLabel imagenLateral;
    private javax.swing.JTextField precio;
    private javax.swing.JLabel textDescripcion;
    private javax.swing.JLabel textDireccion;
    private javax.swing.JLabel textPrecio;
    private javax.swing.JLabel tituloMenu;
    // End of variables declaration//GEN-END:variables
}
