/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazEmpresa;

import java.util.Random;
import gestioninmuebleudc.Edificio;
import gestioninmuebleudc.GestionInmuebleUdc;
import gestioninmuebleudc.Piso;
import gestioninmuebleudc.Local;
import interfazUsuario.MenuDisponible;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Danyysk
 */
public class AgregarEdificio extends javax.swing.JFrame {
    
    //atributos 
    public static int pisoActual; //para imprimir por cual piso vamos al momento de llenar un edificio de n pisos    
    public static int localActual;
    
    
    public AgregarEdificio() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/empresaIcon.png")).getImage());
        this.setLocationRelativeTo(null); //fijamos la ventana en la mitad de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        textNombre = new javax.swing.JLabel();
        textDireccion = new javax.swing.JLabel();
        textPisos = new javax.swing.JLabel();
        textPrecio = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        pisos = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        tituloMenu = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        textLocales = new javax.swing.JLabel();
        local = new javax.swing.JTextField();
        imagenLateral = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, -1));

        textNombre.setText("Nombre Edificio:");
        getContentPane().add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        textDireccion.setText("Direccion Edificio:");
        getContentPane().add(textDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        textPisos.setText("Pisos Edificio:");
        getContentPane().add(textPisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        textPrecio.setText("Precio Alquiler del edificio:");
        getContentPane().add(textPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 115, -1));
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 115, -1));

        pisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pisosActionPerformed(evt);
            }
        });
        getContentPane().add(pisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 115, -1));

        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 115, -1));

        tituloMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tituloMenu.setText("AGREGAR EDIFICIO");
        getContentPane().add(tituloMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        confirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        textLocales.setText("Locales:");
        getContentPane().add(textLocales, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));
        getContentPane().add(local, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 115, -1));

        imagenLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edificioColorFondo.png"))); // NOI18N
        imagenLateral.setText("jLabel2");
        getContentPane().add(imagenLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0); //salimos en caso de que presionen exit
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false); //cerramos la ventana actual y volvemos a la anterior
        MenuEmpresa empresa = new MenuEmpresa(); //creamos un objeto
        empresa.setVisible(true); //ahora a ese objeto le cambiamos a true su atribito de visibilidad para que sea visible
    }//GEN-LAST:event_backActionPerformed

    private void pisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pisosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pisosActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        //aca inicia la verdadera magia
        
        //generamos un codigo random para el id
        Random idRandom = new Random();
        
        //con ayuda del auxiliar le asignamos a este random al auxiliar
        //establecemos que queremos que sea entre 0 y 99 y a eso le sumamos 100
        //es decir, nuestro intervalo sera de 100 a 199
        int auxId = 100 + idRandom.nextInt(99);
        
        String nombreE = nombre.getText();
        
        //tenemos que verificar que el ID del edificio sea unico
        boolean condicion = true;
        for(int i = 0; i < GestionInmuebleUdc.listaInmuebles.size(); i++){
            //comparamos si el id ingresado se encuentra en nuestro arraylist 
            if(auxId == GestionInmuebleUdc.listaInmuebles.get(i).getId()){
                condicion = false; //si se encuentra entonces marcamos como false
            }
        }
        
        if(condicion){
            //esto es para MenuDisponible
            //una clase del package de interfazUsuario, en MenuDisponible se encuentra mas info sobre este proceso
            MenuDisponible.precioStatic = precio.getText();
            MenuDisponible.idStatic = String.valueOf(auxId); //convertimos en String
            
            //creamos el edificio dentro del array de inmuebles
            //colocamos como alquilado a -1 porque puede que el usuario introduzca como su cc a 0, en cambio seria raro que introduzca a -1 como su cc
            GestionInmuebleUdc.listaInmuebles.add(new Edificio(direccion.getText(), Float.parseFloat(precio.getText()), -1,auxId)); //añadimos direccion y precio
            
            //esto es para MenuDisponible

            int aux = 0; //este auxiliar aumentara en 1 con cada iteraccion para asignarle un valor a pisoActual 

            //ahora hacemos un for para iterar la n cantidad de veces que se debe abrir el submenu para agregar piso
            //si se coloco que se tenia 3 pisos se deben crear 3 objetos diferentes de la clase AgregarPisoEdificio
            for(int i = 0; i < Integer.parseInt(pisos.getText()); i++){

                AgregarEdificio.pisoActual = aux + 1;

                this.setVisible(false); //hacemos invisible la interfaz actual

                    //utilizamos esta clase que es un JDialog en lugar de un JFrame
                    AgregarPisoEdificio localMenu = new AgregarPisoEdificio(this,true);
                    localMenu.setModal(true); //volvemos modal
                    localMenu.setVisible(true); //hacemos visible el menu de piso 

                Edificio.agregarPiso(new Piso(direccion.getText(),AgregarPisoEdificio.precioPiso,Piso.numeroPiso,Piso.descripcion,-1,AgregarPisoEdificio.idStatic));//creamos el piso
                aux++;
                
                //convertimos el float en string con String.valueOf
                MenuDisponible.precio3Static = String.valueOf(AgregarPisoEdificio.precioPiso);
                MenuDisponible.id3Static = String.valueOf(AgregarPisoEdificio.idStatic);
                MenuDisponible.descripcion3Static = Piso.descripcion;
                
            }//end for de piso

            JOptionPane.showMessageDialog(null,"Llenado de PISOS compleado","Agregar Edificio",JOptionPane.INFORMATION_MESSAGE);
            aux = 0;
            
            //for de local
            for(int i = 0; i < Integer.parseInt(local.getText()); i++){

                AgregarEdificio.localActual = aux + 1;

                this.setVisible(false); //hacemos invisible la interfaz actual

                //utilizamos esta clase que es un JDialog en lugar de un JFrame
                AgregarLocalEdificio localMenu = new AgregarLocalEdificio(this,true);
                localMenu.setModal(true); //volvemos modal
                localMenu.setVisible(true); //hacemos visible el menu de piso  

                Edificio.agregarLocal(new Local(direccion.getText(),AgregarLocalEdificio.precioLocal,Local.descripcion,-1,AgregarLocalEdificio.idStatic));//creamos el piso
                aux++;
                
                //convertimos el float en string con String.valueOf
                MenuDisponible.precio2Static = String.valueOf(AgregarLocalEdificio.precioLocal);
                MenuDisponible.id2Static = String.valueOf(AgregarLocalEdificio.idStatic);
                MenuDisponible.descripcion2Static = Local.descripcion;
            }
            JOptionPane.showMessageDialog(null,"Llenado de LOCALES compleado","Agregar Edificio",JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(null,"El ID se encuentra\n" + "ocupado por otro inmueble\nIntente de nuevo","Agregar Edificio",JOptionPane.INFORMATION_MESSAGE);
        }   
        
        //esto es un caso especial para ocultar este menu aunque el usuario no abra otros
        //este menu solo se oculta desde otros menus, entonces si no se abren este permanece visible
        if(Integer.parseInt(pisos.getText()) == 0 || Integer.parseInt(local.getText()) == 0){
            this.setVisible(false);
        }
        
        //despues de la iteracion volvemos al menu de empresa  
        MenuEmpresa menu = new MenuEmpresa();
        menu.setVisible(true);   
    }//GEN-LAST:event_confirmarActionPerformed

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEdificio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton confirmar;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton exit;
    private javax.swing.JLabel imagenLateral;
    private javax.swing.JTextField local;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pisos;
    private javax.swing.JTextField precio;
    private javax.swing.JLabel textDireccion;
    private javax.swing.JLabel textLocales;
    private javax.swing.JLabel textNombre;
    private javax.swing.JLabel textPisos;
    private javax.swing.JLabel textPrecio;
    private javax.swing.JLabel tituloMenu;
    // End of variables declaration//GEN-END:variables
}
