 
package interfazEmpresa;

import java.awt.Image; //esta biblioteca sirve para fines esteticos 
import java.awt.Toolkit; // lo mismo
//entre ambas sirven para añadir un icono a la aplicacion en la barra de tareas
 
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null); //con esto centramos la ventana  
    }
    //P - por algun motivo esto no funciona, con esta funcion se deberia crear un icono en la barra de tareas con el archivo seleccionado
    //P - se esta verificando cual es el error, no quitar, despues se documentara
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/edificioBlancoNegro.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frasePart1 = new javax.swing.JLabel();
        frasePart2 = new javax.swing.JLabel();
        autores = new javax.swing.JLabel();
        iniciarSimulacion = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        udcLogo = new javax.swing.JLabel();
        piedraImagen = new javax.swing.JLabel();
        lainSistemasLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frasePart1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        frasePart1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frasePart1.setText("\"¡Todos los Caminos    ");
        getContentPane().add(frasePart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        frasePart2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        frasePart2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frasePart2.setText("Conducen a Piedra!\"");
        getContentPane().add(frasePart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 211, -1, -1));

        autores.setText("Daniel Escalante - Santiago Boyano");
        getContentPane().add(autores, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 254, -1, -1));

        iniciarSimulacion.setText("Iniciar Simulación");
        iniciarSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSimulacionActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        udcLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Oficial_Unicartagena.png"))); // NOI18N
        udcLogo.setText(" ");
        getContentPane().add(udcLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 220, 95));

        piedraImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bannerUdC_Piedra.png"))); // NOI18N
        piedraImagen.setText(" ");
        getContentPane().add(piedraImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        lainSistemasLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lainSistemasLogo.png"))); // NOI18N
        lainSistemasLogo.setText(" ");
        getContentPane().add(lainSistemasLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 290, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
         System.exit(0); //nos salimos si el usuario presiona exit
    }//GEN-LAST:event_exitActionPerformed

    private void iniciarSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSimulacionActionPerformed
        MenuIngreso sc = new MenuIngreso(); //pasamos al MenuIngreso, creando un nuevo objeto
        sc.setVisible(true); //aca cambiamos un valor del JFrame que lo hace invisible, para hacerlo visible ponemos true
        
        //al abrir una nueva ventana debemos cerrar la anterior para no tener dos ventanas
        setVisible(false);
    }//GEN-LAST:event_iniciarSimulacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autores;
    private javax.swing.JButton exit;
    private javax.swing.JLabel frasePart1;
    private javax.swing.JLabel frasePart2;
    private javax.swing.JButton iniciarSimulacion;
    private javax.swing.JLabel lainSistemasLogo;
    private javax.swing.JLabel piedraImagen;
    private javax.swing.JLabel udcLogo;
    // End of variables declaration//GEN-END:variables
}
