 
package interfazEmpresa;

public class MenuEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form MenuEmpresa
     */
    public MenuEmpresa() {
        initComponents();
        this.setLocationRelativeTo(null); //con esta linea centramos la interfaz para que aparezca centrada al usuario
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        edificio = new javax.swing.JButton();
        local = new javax.swing.JButton();
        piso = new javax.swing.JButton();
        finca = new javax.swing.JButton();
        tituloInmobiliaria = new javax.swing.JLabel();
        deseaAgregar = new javax.swing.JLabel();
        gerenteMensaje1 = new javax.swing.JLabel();
        gerenteMensaje2 = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        mas = new javax.swing.JLabel();
        listaDispo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 0, -1, -1));

        edificio.setText("Edificio");
        edificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edificioActionPerformed(evt);
            }
        });
        getContentPane().add(edificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        local.setText("Local");
        local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localActionPerformed(evt);
            }
        });
        getContentPane().add(local, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        piso.setText("Piso");
        piso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pisoActionPerformed(evt);
            }
        });
        getContentPane().add(piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        finca.setText("Finca");
        finca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fincaActionPerformed(evt);
            }
        });
        getContentPane().add(finca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        tituloInmobiliaria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloInmobiliaria.setText("¡Inmobiliaria UdC!");
        getContentPane().add(tituloInmobiliaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 25, -1, -1));

        deseaAgregar.setText("Desea Agregar a Nuestra Empresa");
        getContentPane().add(deseaAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 368, -1, -1));

        gerenteMensaje1.setText("Como nuestro gerente de confianza");
        getContentPane().add(gerenteMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 56, -1, -1));

        gerenteMensaje2.setText(" le ofrecemos una calida bienvenida");
        getContentPane().add(gerenteMensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 78, -1, -1));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User.png"))); // NOI18N
        imagen.setText(" ");
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 100, -1, -1));

        mas.setText("O quizas...");
        getContentPane().add(mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        listaDispo.setText("Ver lista de inmuebles disponibles");
        listaDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDispoActionPerformed(evt);
            }
        });
        getContentPane().add(listaDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0); //con esta linea nos salimos del programa al pulsar exit
    }//GEN-LAST:event_ExitActionPerformed

    private void edificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edificioActionPerformed
        // TODO add your handling code here:
        AgregarEdificio edificio = new AgregarEdificio(); //creamos un objeto de edificio para el menu
        edificio.setVisible(true); //abrimos una ventana del JFrame 
        
        this.setVisible(false); //cerramos la ventana anterior, es decir la de MenuEmpresa, este mismo objeto
    }//GEN-LAST:event_edificioActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        MenuIngreso sc = new MenuIngreso();
        sc.setVisible(true); //aca cambiamos un valor del JFrame que lo hace invisible, para hacerlo visible ponemos true
        //creamos otro objeto para abrir nuevamente el JFrame del Menu de ingreso como si estuvieramos volviendo
        this.setVisible(false); //con esto ocultamos el JFrame del Menu Empresa
    }//GEN-LAST:event_BackActionPerformed

    private void listaDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDispoActionPerformed
      
        ListaDisponible is = new ListaDisponible();
        
        is.setVisible(true); //hacemos visible el nuevo menu
        
        this.setVisible(false); //ocultamos el anterior
    }//GEN-LAST:event_listaDispoActionPerformed

    private void pisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pisoActionPerformed
        // TODO add your handling code here:
        
        AgregarPiso pisoMenu = new AgregarPiso();
        pisoMenu.setVisible(true); //mostramos la nueva interfaz
        this.setVisible(false); //ocultamos esta
    }//GEN-LAST:event_pisoActionPerformed

    private void localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localActionPerformed

    private void fincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fincaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fincaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel deseaAgregar;
    private javax.swing.JButton edificio;
    private javax.swing.JButton finca;
    private javax.swing.JLabel gerenteMensaje1;
    private javax.swing.JLabel gerenteMensaje2;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton listaDispo;
    private javax.swing.JButton local;
    private javax.swing.JLabel mas;
    private javax.swing.JButton piso;
    private javax.swing.JLabel tituloInmobiliaria;
    // End of variables declaration//GEN-END:variables
}
