 
package interfazEmpresa;

import interfazMain.MenuIngreso;

public class MenuEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form MenuEmpresa
     */
    public MenuEmpresa() {
        initComponents();
        this.setLocationRelativeTo(null); //con esta linea centramos la interfaz para que aparezca centrada al usuario
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        edificio = new javax.swing.JButton();
        local = new javax.swing.JButton();
        piso = new javax.swing.JButton();
        finca = new javax.swing.JButton();
        tituloInmobiliaria = new javax.swing.JLabel();
        deseaAgregar = new javax.swing.JLabel();
        gerenteMensaje1 = new javax.swing.JLabel();
        gerenteMensaje2 = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        mas = new javax.swing.JLabel();
        listaDispo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        edificio.setText("Edificio");
        edificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edificioActionPerformed(evt);
            }
        });

        local.setText("Local");
        local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localActionPerformed(evt);
            }
        });

        piso.setText("Piso");
        piso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pisoActionPerformed(evt);
            }
        });

        finca.setText("Finca");
        finca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fincaActionPerformed(evt);
            }
        });

        tituloInmobiliaria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloInmobiliaria.setText("¡Inmobiliaria UdC!");

        deseaAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deseaAgregar.setText("Desea Agregar a Nuestra Empresa");

        gerenteMensaje1.setText("Como nuestro gerente de confianza");

        gerenteMensaje2.setText(" le ofrecemos una calida bienvenida");

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empresaIcon.png"))); // NOI18N
        imagen.setText(" ");

        mas.setText("O quizas...");

        listaDispo.setText("Ver lista de inmuebles disponibles");
        listaDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDispoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(Back)
                .addGap(6, 6, 6)
                .addComponent(Exit))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(tituloInmobiliaria))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(gerenteMensaje1))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(gerenteMensaje2))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(edificio))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(local))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(piso))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(finca))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(mas))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(listaDispo))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deseaAgregar)
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back)
                    .addComponent(Exit))
                .addGap(2, 2, 2)
                .addComponent(tituloInmobiliaria)
                .addGap(6, 6, 6)
                .addComponent(gerenteMensaje1)
                .addGap(6, 6, 6)
                .addComponent(gerenteMensaje2)
                .addGap(16, 16, 16)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deseaAgregar)
                .addGap(18, 18, 18)
                .addComponent(edificio)
                .addGap(7, 7, 7)
                .addComponent(local)
                .addGap(7, 7, 7)
                .addComponent(piso)
                .addGap(7, 7, 7)
                .addComponent(finca)
                .addGap(7, 7, 7)
                .addComponent(mas)
                .addGap(4, 4, 4)
                .addComponent(listaDispo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0); //con esta linea nos salimos del programa al pulsar exit
    }//GEN-LAST:event_ExitActionPerformed

    private void edificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edificioActionPerformed
        // TODO add your handling code here:
        AgregarEdificio edificio = new AgregarEdificio(); //creamos un objeto de edificio para el menu
        edificio.setVisible(true); //abrimos una ventana del JFrame 
        
        this.setVisible(false); //cerramos la ventana anterior, es decir la de MenuEmpresa, este mismo objeto
    }//GEN-LAST:event_edificioActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        MenuIngreso sc = new MenuIngreso();
        sc.setVisible(true); //aca cambiamos un valor del JFrame que lo hace invisible, para hacerlo visible ponemos true
        //creamos otro objeto para abrir nuevamente el JFrame del Menu de ingreso como si estuvieramos volviendo
        this.setVisible(false); //con esto ocultamos el JFrame del Menu Empresa
    }//GEN-LAST:event_BackActionPerformed

    private void listaDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDispoActionPerformed
      
        ListaDisponible is = new ListaDisponible();
        
        is.setVisible(true); //hacemos visible el nuevo menu
        
        this.setVisible(false); //ocultamos el anterior
    }//GEN-LAST:event_listaDispoActionPerformed

    private void pisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pisoActionPerformed
       //creamos un nuevo objeto 
        AgregarPiso pisoMenu = new AgregarPiso();
        pisoMenu.setVisible(true); //mostramos la nueva interfaz
        this.setVisible(false); //ocultamos esta
    }//GEN-LAST:event_pisoActionPerformed

    private void localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localActionPerformed
        //hacmoes lo mismo de arriba pero con este nuevo menu que se abrira de Local
        AgregarLocal local = new AgregarLocal();
        local.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_localActionPerformed

    private void fincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fincaActionPerformed
        AgregarFinca finca = new AgregarFinca();
        finca.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_fincaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel deseaAgregar;
    private javax.swing.JButton edificio;
    private javax.swing.JButton finca;
    private javax.swing.JLabel gerenteMensaje1;
    private javax.swing.JLabel gerenteMensaje2;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton listaDispo;
    private javax.swing.JButton local;
    private javax.swing.JLabel mas;
    private javax.swing.JButton piso;
    private javax.swing.JLabel tituloInmobiliaria;
    // End of variables declaration//GEN-END:variables
}
