/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestioninmuebleudc;

import javax.swing.JTextField;



/**
 *
 * @author Danyysk
 */
public class AgregarPiso extends javax.swing.JFrame {

    /**
     * Creates new form AgregarPiso
     */
    
    public static String descripcion;
    public static int numPiso;
        
    public AgregarPiso() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

     /*
    //esto lo hacemos para poder acceder a datos guardado de un JFrame desde otro
    public void setNumPiso(int numPiso) {
        this.numPiso = numPiso;
        //tenemos que convertir el iblNumPiso en un int antes de poder igualarlo
        iblNumPiso.setText(numPiso);
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
        iblDescripcion.setText(descripcion);
    }
     */
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        tituloMenu = new javax.swing.JLabel();
        textNumPiso = new javax.swing.JLabel();
        textDescripcion = new javax.swing.JLabel();
        iblNumPiso = new javax.swing.JTextField();
        iblDescripcion = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        tituloMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tituloMenu.setText("AGREGAR PISO");
        getContentPane().add(tituloMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 35, -1, -1));

        textNumPiso.setText("Numero de Piso");
        getContentPane().add(textNumPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 70, -1, -1));

        textDescripcion.setText("Descripcion");
        getContentPane().add(textDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 110, -1, -1));

        iblNumPiso.setText(" ");
        iblNumPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iblNumPisoActionPerformed(evt);
            }
        });
        getContentPane().add(iblNumPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 67, 115, -1));

        iblDescripcion.setText(" ");
        iblDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iblDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(iblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 107, 115, -1));

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        //para retroceder
        
        this.setVisible(false); //ocultamos el menu actual
        MenuEmpresa is = new MenuEmpresa();
        
        is.setVisible(true); //hacemos visible el menu anterior
    }//GEN-LAST:event_backActionPerformed

    private void iblNumPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblNumPisoActionPerformed
        // TODO add your handling code here:
        String aux; //necesitamos la ayuda de un auxiliar para hacer una pequeña conversion
        aux = iblNumPiso.getText(); //cuando el usuario introduce un valor eso es un String, pero numPiso es un int
        
        numPiso = Integer.parseInt(aux);
    }//GEN-LAST:event_iblNumPisoActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        // TODO add your handling code here:
        //String descripcionP = descripcion.getText();
        //String numPisoP = numPiso.getText();
        
           
        
    }//GEN-LAST:event_confirmarActionPerformed

    private void iblDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iblDescripcionActionPerformed
        // TODO add your handling code here:
        descripcion = iblDescripcion.getText();
    }//GEN-LAST:event_iblDescripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPiso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton confirmar;
    private javax.swing.JButton exit;
    private javax.swing.JTextField iblDescripcion;
    private javax.swing.JTextField iblNumPiso;
    private javax.swing.JLabel textDescripcion;
    private javax.swing.JLabel textNumPiso;
    private javax.swing.JLabel tituloMenu;
    // End of variables declaration//GEN-END:variables
}
