/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestioninmuebleudc;
 
import java.awt.Image; //esta biblioteca sirve para fines esteticos 
import java.awt.Toolkit; // lo mismo
//entre ambas sirven para añadir un icono a la aplicacion en la barra de tareas

/**
 *
 * @author Danyysk
 */
public class MenuIngreso extends javax.swing.JFrame {

    /**
     * Creates new form MenuIngreso
     */
    public MenuIngreso() {
        initComponents();
        this.setLocationRelativeTo(null); //con esta linea centramos la interfaz para que aparezca centrada al usuario
    }
    
    //esto sirve para colocar el icono a la aplicacion, este icono se muestra en la barra de tareas
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/lain.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jButtonEmpresa = new javax.swing.JButton();
        jButtonPersona = new javax.swing.JButton();
        JLabelBienvenido = new javax.swing.JLabel();
        jLabelLain = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jLabelMensajeServicios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(720, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        jButtonEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEmpresa.setText("Empresa");
        jButtonEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        jButtonPersona.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPersona.setText("Persona");
        getContentPane().add(jButtonPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        JLabelBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLabelBienvenido.setText("¡Bienvenido!");
        getContentPane().add(JLabelBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 130, 40));

        jLabelLain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lain.png"))); // NOI18N
        jLabelLain.setText("jLabel1");
        getContentPane().add(jLabelLain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 410));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabelFondo.setText(" ");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 410));

        jLabelMensajeServicios.setText("Desea usar nuestros servicios en su vista como:");
        getContentPane().add(jLabelMensajeServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 280, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0); //para que se salga al pursar el salir
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpresaActionPerformed
        // TODO add your handling code here:
        //con esto lo que estamos haciendo es llamar a otro JFrame, 
        //cuando el usuario presiona el Boton "Empresa" se llama a otro JFrame con opciones de empresa
        MenuEmpresa empresa = new MenuEmpresa(); //JFrame de empresa
        empresa.setVisible(true); //aca cambiamos un valor del JFrame que lo hace invisible, para hacerlo visible ponemos true
     
        setVisible(false); //hacemos invisible el JFrame de MenuIngreso
    }//GEN-LAST:event_jButtonEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelBienvenido;
    private javax.swing.JButton jButtonEmpresa;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPersona;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLain;
    private javax.swing.JLabel jLabelMensajeServicios;
    // End of variables declaration//GEN-END:variables
}
