/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazUsuario;

import gestioninmuebleudc.GestionInmuebleUdc;
import gestioninmuebleudc.Usuario;
import static interfazUsuario.InicioSesion.sesionActivaUbic;
import javax.swing.JOptionPane;

public class GestorPago extends javax.swing.JFrame {
    
    public GestorPago() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static String estratoStatic;
    public static float dineroStatic;
    
    public static float gasStatic;
    public static float aguaStatic;
    public static float luzStatic;
    
    public void actualizarRecibo(){
        gas.setText(String.valueOf(gasStatic));
        agua.setText(String.valueOf(aguaStatic));
        luz.setText(String.valueOf(luzStatic));
    }
    
    public void actualizarDinero(){
        dinero.setText(String.valueOf(dineroStatic));
    }
    
    public void actualizarEstrato(){
        estrato.setText(estratoStatic);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pagarArriendo = new javax.swing.JButton();
        pagarGas = new javax.swing.JButton();
        pagarAgua = new javax.swing.JButton();
        textEstrato = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        estrato = new javax.swing.JLabel();
        gas = new javax.swing.JLabel();
        agua = new javax.swing.JLabel();
        luz = new javax.swing.JLabel();
        textDinero = new javax.swing.JLabel();
        dinero = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        pagarLuz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pagarArriendo.setText("Pagar Arriendo");
        pagarArriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarArriendoActionPerformed(evt);
            }
        });

        pagarGas.setText("Pagar Gas");
        pagarGas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarGasActionPerformed(evt);
            }
        });

        pagarAgua.setText("Pagar Agua");
        pagarAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarAguaActionPerformed(evt);
            }
        });

        textEstrato.setText("Su estrato:");

        jLabel2.setText("Recibo Gas:");

        jLabel3.setText("Recibo Agua:");

        jLabel4.setText("Recibo Luz:");

        estrato.setText("null");

        gas.setText("aun no...");

        agua.setText("aun no...");

        luz.setText("aun no...");

        textDinero.setText("Dinero:");

        dinero.setText("null");

        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo.setText("Gestor Pago");

        pagarLuz.setText("Pagar Luz");
        pagarLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarLuzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pagarLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pagarAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pagarArriendo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pagarGas, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textEstrato)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(estrato))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agua)
                                    .addComponent(gas)
                                    .addComponent(luz)
                                    .addComponent(titulo))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDinero)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dinero)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(back))
                .addGap(9, 9, 9)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textEstrato)
                            .addComponent(estrato))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(gas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(agua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(luz)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textDinero)
                        .addComponent(dinero)))
                .addGap(40, 40, 40)
                .addComponent(pagarArriendo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pagarGas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagarAgua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagarLuz)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagarGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarGasActionPerformed
        
        if(dineroStatic >= Float.parseFloat(gas.getText())){
            //disminuimos el dinero
            dineroStatic = dineroStatic - Float.parseFloat(gas.getText());
            //actualizamos en el arraylist
            GestionInmuebleUdc.listaUsuarios.get(InicioSesion.sesionActivaUbic).setDinero(-1*(dineroStatic - Float.parseFloat(gas.getText())));

            //ahora creamos la factura, que sera un movimiento bancario
            GestionInmuebleUdc.listaMovimientosBancarios.add(new gestioninmuebleudc.MovimientoBancario("Pago Recibo Gas",Usuario.time, gasStatic, GestionInmuebleUdc.listaUsuarios.get(sesionActivaUbic).getNombre(), "Gas Udc"));
            JOptionPane.showMessageDialog(null, "Recibo pagado con exito", "Transaccion Exitosa", JOptionPane.INFORMATION_MESSAGE);
            //actualizamos informacion del menu, actualizando el dinero que se muestra y el gas en tiempo real
            gas.setText(String.valueOf(0));
            dinero.setText(String.valueOf(dineroStatic));
        } else {
            JOptionPane.showMessageDialog(null, "No cuenta con suficiente dinero...", "Transaccion Fallida", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_pagarGasActionPerformed

    private void pagarArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarArriendoActionPerformed
 
            //poner que el usuario ingrese el codigo del inmueble
            String s = JOptionPane.showInputDialog(null, "Ingrese el ID del inmueble", "Pagar Arriendo", JOptionPane.QUESTION_MESSAGE);
            
            int auxCase = 0;
            float deuda = 0;
            
            for(int i = 0; i < GestionInmuebleUdc.listaInmuebles.size(); i++){
                //aca determinamos si se encontro o no el id introducido por el usuario
                if(Integer.parseInt(s) == GestionInmuebleUdc.listaInmuebles.get(i).getId() ){
                    //a partir del id podemos determinar el tipo de inmueble
                    //100 a 199 = edificio - paga 40% de impuesto
                    //200 a 299 = finca - paga 10% de impuesto
                    //300 a 399 = local - paga 30% de impuesto
                    //400 a 499 = piso - paga 20% de impuesto
                    
                    
                    if(GestionInmuebleUdc.listaInmuebles.get(i).getId() > 99 && GestionInmuebleUdc.listaInmuebles.get(i).getId() < 200){
                        auxCase = 1;
                    } else if(GestionInmuebleUdc.listaInmuebles.get(i).getId() > 199 && GestionInmuebleUdc.listaInmuebles.get(i).getId() < 300){
                        auxCase = 2;
                    } else if(GestionInmuebleUdc.listaInmuebles.get(i).getId() > 299 && GestionInmuebleUdc.listaInmuebles.get(i).getId() < 400){
                        auxCase = 3;
                    } else if(GestionInmuebleUdc.listaInmuebles.get(i).getId() > 399 && GestionInmuebleUdc.listaInmuebles.get(i).getId() < 500){
                        auxCase = 4;
                    } 
                    
                    switch (auxCase){
                        case 1:
                            //creamos un objeto de Edificio
                            gestioninmuebleudc.Edificio next = new gestioninmuebleudc.Edificio("",GestionInmuebleUdc.listaInmuebles.get(i).getPrecioAlquiler(),0,0);
                            //enviamos la posicion i del arraylist al metodo consultarPrecioAlquiler donde se le sumara
                            //un impuesto al precio total a pagar
                            //si el usuario dijo que costaba 100 alquilar su piso, a ese 100 se le aplica un impuesto
                            //el impuesto varia dependiendo del objeto y la clase, es decir, estamos aplicando abstraccion y polimorfismo
                            deuda = next.consultarPrecioAlquiler(i);
                            //gestioninmuebleudc.Edificio.                                    
                            break;
                        case 2:
                            gestioninmuebleudc.Finca next2 = new gestioninmuebleudc.Finca("",GestionInmuebleUdc.listaInmuebles.get(i).getPrecioAlquiler(),"",0,0); 
                            deuda = next2.consultarPrecioAlquiler(i);
                            break;
                        case 3:
                            gestioninmuebleudc.Local next3 = new gestioninmuebleudc.Local("",GestionInmuebleUdc.listaInmuebles.get(i).getPrecioAlquiler(),"",0,0); 
                            deuda = next3.consultarPrecioAlquiler(i);
                            break;
                        case 4:    
                            gestioninmuebleudc.Piso next4 = new gestioninmuebleudc.Piso("",GestionInmuebleUdc.listaInmuebles.get(i).getPrecioAlquiler(),0,"",0,0); 
                            deuda = next4.consultarPrecioAlquiler(i);
                            break;
                    }
                    
                    if(dineroStatic >= deuda){
                        //ahora creamos la factura, que sera un movimiento bancario
                        GestionInmuebleUdc.listaMovimientosBancarios.add(new gestioninmuebleudc.MovimientoBancario("Pago Renta",Usuario.time, deuda, GestionInmuebleUdc.listaUsuarios.get(sesionActivaUbic).getNombre(), "Inmobiliaria Udc"));
                        JOptionPane.showMessageDialog(null, "Arriendo (mas impuestos): " + deuda + "\nRecibo pagado con exito", "Transaccion Exitosa", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Arriendo (mas impuestos): " + deuda + "\nDinero Insuficiente", "Transaccion Fallida", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                   //inmueble no encontrado
                    JOptionPane.showMessageDialog(null, "ID del Inmueble no encontrado", "Transaccion Fallida", JOptionPane.INFORMATION_MESSAGE);
                } //end else de inmueble no encontrado
            } //end for
    }//GEN-LAST:event_pagarArriendoActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        
        InicioExitoso back = new InicioExitoso();
        back.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void pagarAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarAguaActionPerformed
        if(dineroStatic >= Float.parseFloat(agua.getText())){
            //disminuimos el dinero
            dineroStatic = dineroStatic - Float.parseFloat(agua.getText());
            //actualizamos en el arraylist
            GestionInmuebleUdc.listaUsuarios.get(InicioSesion.sesionActivaUbic).setDinero(-1*(dineroStatic - Float.parseFloat(gas.getText())));

            //ahora creamos la factura, que sera un movimiento bancario
            GestionInmuebleUdc.listaMovimientosBancarios.add(new gestioninmuebleudc.MovimientoBancario("Pago Recibo Agua",Usuario.time, aguaStatic, GestionInmuebleUdc.listaUsuarios.get(sesionActivaUbic).getNombre(), "Aguas Udc"));
            JOptionPane.showMessageDialog(null, "Recibo pagado con exito", "Transaccion Exitosa", JOptionPane.INFORMATION_MESSAGE);
            agua.setText(String.valueOf(0));
            dinero.setText(String.valueOf(dineroStatic));
        } else {
            JOptionPane.showMessageDialog(null, "No cuenta con suficiente dinero...", "Transaccion Fallida", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_pagarAguaActionPerformed

    private void pagarLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarLuzActionPerformed
        if(dineroStatic >= Float.parseFloat(luz.getText())){
            //disminuimos el dinero
            dineroStatic = dineroStatic - Float.parseFloat(luz.getText());
            //actualizamos en el arraylist
            GestionInmuebleUdc.listaUsuarios.get(InicioSesion.sesionActivaUbic).setDinero(-1*(dineroStatic - Float.parseFloat(gas.getText())));

            //ahora creamos la factura, que sera un movimiento bancario
            GestionInmuebleUdc.listaMovimientosBancarios.add(new gestioninmuebleudc.MovimientoBancario("Pago Recibo Luz",Usuario.time, luzStatic, GestionInmuebleUdc.listaUsuarios.get(sesionActivaUbic).getNombre(), "Luz Udc"));
            JOptionPane.showMessageDialog(null, "Recibo pagado con exito", "Transaccion Exitosa", JOptionPane.INFORMATION_MESSAGE);
            luz.setText(String.valueOf(0));
            dinero.setText(String.valueOf(dineroStatic));
        } else {
            JOptionPane.showMessageDialog(null, "No cuenta con suficiente dinero...", "Transaccion Fallida", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_pagarLuzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agua;
    private javax.swing.JButton back;
    private javax.swing.JLabel dinero;
    private javax.swing.JLabel estrato;
    private javax.swing.JButton exit;
    private javax.swing.JLabel gas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel luz;
    private javax.swing.JButton pagarAgua;
    private javax.swing.JButton pagarArriendo;
    private javax.swing.JButton pagarGas;
    private javax.swing.JButton pagarLuz;
    private javax.swing.JLabel textDinero;
    private javax.swing.JLabel textEstrato;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
