/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazUsuario;

import gestioninmuebleudc.GestionInmuebleUdc;
import gestioninmuebleudc.Usuario;
import static interfazUsuario.InicioSesion.sesionActivaUbic;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class GestorPago extends javax.swing.JFrame {
    
    public GestorPago() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/empresaIcon.png")).getImage());
        this.setLocationRelativeTo(null);
    }

    public static String estratoStatic;
    public static float dineroStatic;
    
    public static float gasStatic;
    public static float aguaStatic;
    public static float luzStatic;
    
    public void actualizarRecibo(){
        gas.setText(String.valueOf(gasStatic));
        agua.setText(String.valueOf(aguaStatic));
        luz.setText(String.valueOf(luzStatic));
    }
    
    public void actualizarDinero(){
        dinero.setText(String.valueOf(dineroStatic));
    }
    
    public void actualizarEstrato(){
        estrato.setText(estratoStatic);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pagarArriendo = new javax.swing.JButton();
        pagarGas = new javax.swing.JButton();
        pagarAgua = new javax.swing.JButton();
        textEstrato = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        estrato = new javax.swing.JLabel();
        gas = new javax.swing.JLabel();
        agua = new javax.swing.JLabel();
        luz = new javax.swing.JLabel();
        textDinero = new javax.swing.JLabel();
        dinero = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        pagarLuz = new javax.swing.JButton();
        imagenLateral = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pagarArriendo.setText("Pagar Arriendo");
        pagarArriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarArriendoActionPerformed(evt);
            }
        });
        getContentPane().add(pagarArriendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        pagarGas.setText("Pagar Gas");
        pagarGas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarGasActionPerformed(evt);
            }
        });
        getContentPane().add(pagarGas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 109, -1));

        pagarAgua.setText("Pagar Agua");
        pagarAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarAguaActionPerformed(evt);
            }
        });
        getContentPane().add(pagarAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 109, -1));

        textEstrato.setText("Su estrato:");
        getContentPane().add(textEstrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jLabel2.setText("Recibo Gas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel3.setText("Recibo Agua:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jLabel4.setText("Recibo Luz:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        estrato.setText("null");
        getContentPane().add(estrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        gas.setText("aun no...");
        getContentPane().add(gas, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        agua.setText("aun no...");
        getContentPane().add(agua, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        luz.setText("aun no...");
        getContentPane().add(luz, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        textDinero.setText("Dinero:");
        getContentPane().add(textDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        dinero.setText("null");
        getContentPane().add(dinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo.setText("Gestor Pago");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, -1));

        pagarLuz.setText("Pagar Luz");
        pagarLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarLuzActionPerformed(evt);
            }
        });
        getContentPane().add(pagarLuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 109, -1));

        imagenLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edificioColorFondo.png"))); // NOI18N
        imagenLateral.setText("jLabel2");
        getContentPane().add(imagenLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagarGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarGasActionPerformed
        
        if(dineroStatic >= Float.parseFloat(gas.getText())){
            //disminuimos el dinero
            dineroStatic = dineroStatic - Float.parseFloat(gas.getText());
            //actualizamos en el arraylist
            GestionInmuebleUdc.listaUsuarios.get(InicioSesion.sesionActivaUbic).setDinero(-1*(dineroStatic - Float.parseFloat(gas.getText())));

            //ahora creamos la factura, que sera un movimiento bancario
            GestionInmuebleUdc.listaMovimientosBancarios.add(new gestioninmuebleudc.MovimientoBancario("Ingreso","Pago Recibo Gas",Usuario.time, gasStatic, GestionInmuebleUdc.listaUsuarios.get(sesionActivaUbic).getNombre(), "Gas Udc"));
            JOptionPane.showMessageDialog(null, "Recibo pagado con exito", "Transaccion Exitosa", JOptionPane.INFORMATION_MESSAGE);
            //actualizamos informacion del menu, actualizando el dinero que se muestra y el gas en tiempo real
            gas.setText(String.valueOf(0));
            dinero.setText(String.valueOf(dineroStatic));
        } else {
            JOptionPane.showMessageDialog(null, "No cuenta con suficiente dinero...", "Transaccion Fallida", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_pagarGasActionPerformed

    private void pagarArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarArriendoActionPerformed
 
            //poner que el usuario ingrese el codigo del inmueble
            String s = JOptionPane.showInputDialog(null, "Ingrese el ID del inmueble", "Pagar Arriendo", JOptionPane.QUESTION_MESSAGE);
            
            int auxCase = 0;
            float deuda = 0;
            
            for(int i = 0; i < GestionInmuebleUdc.listaInmuebles.size(); i++){
                //aca determinamos si se encontro o no el id introducido por el usuario
                if(Integer.parseInt(s) == GestionInmuebleUdc.listaInmuebles.get(i).getId() ){
                    //a partir del id podemos determinar el tipo de inmueble
                    //100 a 199 = edificio - paga 40% de impuesto
                    //200 a 299 = finca - paga 10% de impuesto
                    //300 a 399 = local - paga 30% de impuesto
                    //400 a 499 = piso - paga 20% de impuesto
                    
                    
                    if(GestionInmuebleUdc.listaInmuebles.get(i).getId() > 99 && GestionInmuebleUdc.listaInmuebles.get(i).getId() < 200){
                        auxCase = 1;
                    } else if(GestionInmuebleUdc.listaInmuebles.get(i).getId() > 199 && GestionInmuebleUdc.listaInmuebles.get(i).getId() < 300){
                        auxCase = 2;
                    } else if(GestionInmuebleUdc.listaInmuebles.get(i).getId() > 299 && GestionInmuebleUdc.listaInmuebles.get(i).getId() < 400){
                        auxCase = 3;
                    } else if(GestionInmuebleUdc.listaInmuebles.get(i).getId() > 399 && GestionInmuebleUdc.listaInmuebles.get(i).getId() < 500){
                        auxCase = 4;
                    } 
                    
                    switch (auxCase){
                        case 1:
                            //creamos un objeto de Edificio
                            gestioninmuebleudc.Edificio next = new gestioninmuebleudc.Edificio("",GestionInmuebleUdc.listaInmuebles.get(i).getPrecioAlquiler(),0,0);
                            //enviamos la posicion i del arraylist al metodo consultarPrecioAlquiler donde se le sumara
                            //un impuesto al precio total a pagar
                            //si el usuario dijo que costaba 100 alquilar su piso, a ese 100 se le aplica un impuesto
                            //el impuesto varia dependiendo del objeto y la clase, es decir, estamos aplicando abstraccion y polimorfismo
                            deuda = next.consultarPrecioAlquiler(i);
                            //gestioninmuebleudc.Edificio.                                    
                            break;
                        case 2:
                            gestioninmuebleudc.Finca next2 = new gestioninmuebleudc.Finca("",GestionInmuebleUdc.listaInmuebles.get(i).getPrecioAlquiler(),"",0,0); 
                            deuda = next2.consultarPrecioAlquiler(i);
                            break;
                        case 3:
                            gestioninmuebleudc.Local next3 = new gestioninmuebleudc.Local("",GestionInmuebleUdc.listaInmuebles.get(i).getPrecioAlquiler(),"",0,0); 
                            deuda = next3.consultarPrecioAlquiler(i);
                            break;
                        case 4:    
                            gestioninmuebleudc.Piso next4 = new gestioninmuebleudc.Piso("",GestionInmuebleUdc.listaInmuebles.get(i).getPrecioAlquiler(),0,"",0,0); 
                            deuda = next4.consultarPrecioAlquiler(i);
                            break;
                    }
                    
                    if(dineroStatic >= deuda){
                        //ahora creamos la factura, que sera un movimiento bancario
                        GestionInmuebleUdc.listaMovimientosBancarios.add(new gestioninmuebleudc.MovimientoBancario("Ingreso","Pago Renta",Usuario.time, deuda, GestionInmuebleUdc.listaUsuarios.get(sesionActivaUbic).getNombre(), "Inmobiliaria Udc"));
                        JOptionPane.showMessageDialog(null, "Arriendo (mas impuestos): " + deuda + "\nRecibo pagado con exito", "Transaccion Exitosa", JOptionPane.INFORMATION_MESSAGE);
                        dinero.setText(String.valueOf(dineroStatic));
                    } else {
                        JOptionPane.showMessageDialog(null, "Arriendo (mas impuestos): " + deuda + "\nDinero Insuficiente", "Transaccion Fallida", JOptionPane.INFORMATION_MESSAGE);
                    }
                    
                    
                } else {
                   //inmueble no encontrado
                    JOptionPane.showMessageDialog(null, "ID del Inmueble no encontrado", "Transaccion Fallida", JOptionPane.INFORMATION_MESSAGE);
                } //end else de inmueble no encontrado
            } //end for
    }//GEN-LAST:event_pagarArriendoActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        
        InicioExitoso back = new InicioExitoso();
        back.actualizarFecha(Usuario.time);
        back.actualizarDinero();
        back.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void pagarAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarAguaActionPerformed
        if(dineroStatic >= Float.parseFloat(agua.getText())){
            //disminuimos el dinero
            dineroStatic = dineroStatic - Float.parseFloat(agua.getText());
            //actualizamos en el arraylist
            GestionInmuebleUdc.listaUsuarios.get(InicioSesion.sesionActivaUbic).setDinero(-1*(dineroStatic - Float.parseFloat(gas.getText())));

            //ahora creamos la factura, que sera un movimiento bancario
            GestionInmuebleUdc.listaMovimientosBancarios.add(new gestioninmuebleudc.MovimientoBancario("Ingreso","Pago Recibo Agua",Usuario.time, aguaStatic, GestionInmuebleUdc.listaUsuarios.get(sesionActivaUbic).getNombre(), "Aguas Udc"));
            JOptionPane.showMessageDialog(null, "Recibo pagado con exito", "Transaccion Exitosa", JOptionPane.INFORMATION_MESSAGE);
            agua.setText(String.valueOf(0));
            dinero.setText(String.valueOf(dineroStatic));
        } else {
            JOptionPane.showMessageDialog(null, "No cuenta con suficiente dinero...", "Transaccion Fallida", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_pagarAguaActionPerformed

    private void pagarLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarLuzActionPerformed
        if(dineroStatic >= Float.parseFloat(luz.getText())){
            //disminuimos el dinero
            dineroStatic = dineroStatic - Float.parseFloat(luz.getText());
            //actualizamos en el arraylist
            GestionInmuebleUdc.listaUsuarios.get(InicioSesion.sesionActivaUbic).setDinero(-1*(dineroStatic - Float.parseFloat(gas.getText())));

            //ahora creamos la factura, que sera un movimiento bancario
            GestionInmuebleUdc.listaMovimientosBancarios.add(new gestioninmuebleudc.MovimientoBancario("Ingreso","Pago Recibo Luz",Usuario.time, luzStatic, GestionInmuebleUdc.listaUsuarios.get(sesionActivaUbic).getNombre(), "Luz Udc"));
            JOptionPane.showMessageDialog(null, "Recibo pagado con exito", "Transaccion Exitosa", JOptionPane.INFORMATION_MESSAGE);
            luz.setText(String.valueOf(0));
            dinero.setText(String.valueOf(dineroStatic));
        } else {
            JOptionPane.showMessageDialog(null, "No cuenta con suficiente dinero...", "Transaccion Fallida", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_pagarLuzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agua;
    private javax.swing.JButton back;
    private javax.swing.JLabel dinero;
    private javax.swing.JLabel estrato;
    private javax.swing.JButton exit;
    private javax.swing.JLabel gas;
    private javax.swing.JLabel imagenLateral;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel luz;
    private javax.swing.JButton pagarAgua;
    private javax.swing.JButton pagarArriendo;
    private javax.swing.JButton pagarGas;
    private javax.swing.JButton pagarLuz;
    private javax.swing.JLabel textDinero;
    private javax.swing.JLabel textEstrato;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
