/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazUsuario;
import gestioninmuebleudc.GestionInmuebleUdc;
import gestioninmuebleudc.Usuario;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Danyysk
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null); //centramos el menu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        textUsser = new javax.swing.JLabel();
        textContraseña = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        usser = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        textUsser.setText("Nombre de Usuario");

        textContraseña.setText("Contraseña");

        confirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmar.setText("confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        usser.setText("danyysk");
        usser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usserActionPerformed(evt);
            }
        });

        contraseña.setText("123");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textUsser)
                    .addComponent(textContraseña))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exit))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(contraseña, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(usser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(confirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(back))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textUsser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textContraseña)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(confirmar)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       this.setVisible(false); //hacemos invisible el menu actual
       MenuUsuario back = new MenuUsuario();
       back.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        
        boolean inicioExitoso = false;
        
        
        
        //colocamos esto como ayuda para saber que ingresamos 
        System.out.println("--------------");
        System.out.println("USTED INGRESO: ");
        System.out.println("Usser: '" + usser.getText() + "'");
        System.out.println("Contrasenia: '" + contraseña.getText() + "'");
        System.out.println("--------------");
        System.out.println("PERSONAS REGISTRADAS: ");
        
        //un for para precisar si el usuario introducido fue encontrado o no
        //el for itera siempre que i sea menor que el tamaño del arraylist
        for(int i = 0; i < GestionInmuebleUdc.listaUsuarios.size(); i++){
            
            //y esto para saber cuales usuarios si estan registrados
            System.out.println("Usser: '" + GestionInmuebleUdc.listaUsuarios.get(i).getNombre() + "'");
            System.out.println("contrasenia: '" + GestionInmuebleUdc.listaUsuarios.get(i).getContraseña() + "'");
            System.out.println("...............");
            
            //ahora comparamos si el nombre ingresado se encuentra en el arraylist
            if(usser.getText().equals(GestionInmuebleUdc.listaUsuarios.get(i).getNombre())){
                //si el nombre se encuentra marcamos la posicion i
                if(contraseña.getText().equals(GestionInmuebleUdc.listaUsuarios.get(i).getContraseña())){
                    inicioExitoso = true;//marcamos que si se pudo iniciar sesion
                    break;
                }
            } //end if externo
        }//end for
        
        
        this.setVisible(false);
        //si el inicio de sesion fue fallido entonces
        if(!inicioExitoso){
            
            JOptionPane.showMessageDialog(null,"Nombre de usuario o contraseña incorrecta :/","Inicio de Sesion Fallido",JOptionPane.INFORMATION_MESSAGE);
            //y ahora nos devolvemos al menu anterior
            MenuUsuario back = new MenuUsuario();
            back.setVisible(true);
            
        } else { //si el inicio fue exitoso entonces creamos un nuevo objeto
            Usuario.time = LocalDate.parse("2024-06-15"); //aca asignamos un valor al atributo static "time" para que inicie con algo 
            
            InicioExitoso next = new InicioExitoso();
            next.setVisible(true);
            
            //le mandamos al metodo actualizarFecha de este nuevo objeto un LocalDate 
            next.actualizarFecha(Usuario.time);
        }
        
    }//GEN-LAST:event_confirmarActionPerformed

    private void usserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton confirmar;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JButton exit;
    private javax.swing.JLabel textContraseña;
    private javax.swing.JLabel textUsser;
    private javax.swing.JTextField usser;
    // End of variables declaration//GEN-END:variables
}
