/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazUsuario;
import gestioninmuebleudc.GestionInmuebleUdc;
import gestioninmuebleudc.Usuario;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Danyysk
 */
public class InicioSesion extends javax.swing.JFrame {

    public static String ccStatic;
    public static int sesionActivaUbic;
    
    public InicioSesion() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/empresaIcon.png")).getImage());
        this.setLocationRelativeTo(null); //centramos el menu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        textUsser = new javax.swing.JLabel();
        textContraseña = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        usser = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        imagenLateral = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, -1));

        textUsser.setText("Nombre de Usuario");
        getContentPane().add(textUsser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        textContraseña.setText("Contraseña");
        getContentPane().add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        confirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmar.setText("confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        usser.setText("danyysk");
        usser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usserActionPerformed(evt);
            }
        });
        getContentPane().add(usser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 120, -1));

        contraseña.setText("123");
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 120, -1));

        imagenLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edificioColorFondo.png"))); // NOI18N
        imagenLateral.setText("jLabel2");
        getContentPane().add(imagenLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 380));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Inicio de Sesion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       this.setVisible(false); //hacemos invisible el menu actual
       MenuUsuario back = new MenuUsuario();
       back.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        
        boolean inicioExitoso = false;

        //colocamos esto como ayuda para saber que ingresamos 
        System.out.println("--------------");
        System.out.println("USTED INGRESO: ");
        System.out.println("Usser: '" + usser.getText() + "'");
        System.out.println("Contrasenia: '" + contraseña.getText() + "'");
        System.out.println("--------------");
        System.out.println("PERSONAS REGISTRADAS: ");
        
        //un for para precisar si el usuario introducido fue encontrado o no
        //el for itera siempre que i sea menor que el tamaño del arraylist
        for(int i = 0; i < GestionInmuebleUdc.listaUsuarios.size(); i++){
            
            //y esto para saber cuales usuarios si estan registrados
            System.out.println("Usser: '" + GestionInmuebleUdc.listaUsuarios.get(i).getNombre() + "'");
            System.out.println("contrasenia: '" + GestionInmuebleUdc.listaUsuarios.get(i).getContraseña() + "'");
            System.out.println("...............");
            
            //ahora comparamos si el nombre ingresado se encuentra en el arraylist
            if(usser.getText().equals(GestionInmuebleUdc.listaUsuarios.get(i).getNombre())){
                //si el nombre se encuentra marcamos la posicion i
                if(contraseña.getText().equals(GestionInmuebleUdc.listaUsuarios.get(i).getContraseña())){
                    inicioExitoso = true;//marcamos que si se pudo iniciar sesion
                    break;
                }
            } //end if externo
        }//end for
        
        
        this.setVisible(false);
        //si el inicio de sesion fue fallido entonces
        if(!inicioExitoso){
            
            JOptionPane.showMessageDialog(null,"Nombre de usuario o contraseña incorrecta :/","Inicio de Sesion Fallido",JOptionPane.INFORMATION_MESSAGE);
            //y ahora nos devolvemos al menu anterior
            MenuUsuario back = new MenuUsuario();
            back.setVisible(true);
            
        } else { //si el inicio fue exitoso entonces creamos un nuevo objeto
            
            //si se pudo iniciar sesion es porque esta registrado
            //asi que confiamos en que ya hay al menos alguien registrado y en el arraylist de listaUsuarios
            for(int i = 0; i < GestionInmuebleUdc.listaUsuarios.size(); i++){
                //buscamos un usuario registrado con el mismo nombre, y entonces diremos que la posicion i
                //donde se encuentra la cc, sera igual a ccStatic, esto lo hacemos porque ya sabemos que el inicio
                //de sesion fue exitoso
                if(usser.getText().equals(GestionInmuebleUdc.listaUsuarios.get(i).getNombre())){
                    /*
                    ccStatic obtiene el valor de la cedula de la ultima persona en iniciar sesion, esta persona pasa al menu
                    de la clase InicioExitoso, alli le asignaremos una cc al inmueble que alquile como forma de  identificador
                    para no tener que iterar en un for o preguntar la cc, el programa automaticamente sabe que la ultima persona
                    en iniciar sesion (su cc) sera la de la persona que quiere alquilar, ya que para alquilar primero necesitas
                    iniciar sesion
                    */
                    ccStatic = GestionInmuebleUdc.listaUsuarios.get(i).getCedula();
                    sesionActivaUbic = i;
                    break;
                } 
            } //end for

            //esto es para evitar que se le asigne siempre el LocalDate.parse("2024-"06-"15") cada vez
            //que se inicia sesion
            LocalDate aux = LocalDate.parse("2000-01-01");
            if(Usuario.time.equals(aux)){
                Usuario.time = LocalDate.parse("2024-06-15"); //aca asignamos un valor al atributo static "time" para que inicie con algo 
            } 
   
            InicioExitoso next = new InicioExitoso();
            //next.actualizarFecha(Usuario.time);
            next.actualizarDinero();
            next.setVisible(true);
            
            //le mandamos al metodo actualizarFecha de este nuevo objeto un LocalDate 
            next.actualizarFecha(Usuario.time);
        } //end inicio exitoso
        
    }//GEN-LAST:event_confirmarActionPerformed

    private void usserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton confirmar;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JButton exit;
    private javax.swing.JLabel imagenLateral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel textContraseña;
    private javax.swing.JLabel textUsser;
    private javax.swing.JTextField usser;
    // End of variables declaration//GEN-END:variables
}
