/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazUsuario;
import gestioninmuebleudc.GestionInmuebleUdc;
import gestioninmuebleudc.Usuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Danyysk
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/empresaIcon.png")).getImage());
        this.setLocationRelativeTo(null); //centramos el menu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        textUsser = new javax.swing.JLabel();
        textCedula = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        usser = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        textEdad = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        textSexo = new javax.swing.JLabel();
        sexo = new javax.swing.JTextField();
        textFoto = new javax.swing.JLabel();
        foto = new javax.swing.JTextField();
        textContraseña = new javax.swing.JLabel();
        textRegistro = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        contraseña2 = new javax.swing.JPasswordField();
        textContraseña2 = new javax.swing.JLabel();
        textEstrato = new javax.swing.JLabel();
        estrato = new javax.swing.JTextField();
        imagenLateral = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        textUsser.setText("Nombre de Usuario");
        getContentPane().add(textUsser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        textCedula.setText("Cedula");
        getContentPane().add(textCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        confirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmar.setText("confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        usser.setText("danyysk");
        getContentPane().add(usser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 120, -1));

        cedula.setText("123");
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 120, -1));

        textEdad.setText("Edad");
        getContentPane().add(textEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        edad.setText("1");
        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 120, -1));

        textSexo.setText("Sexo");
        getContentPane().add(textSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        sexo.setText("m");
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });
        getContentPane().add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 120, -1));

        textFoto.setText("Foto");
        getContentPane().add(textFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        foto.setText("m");
        foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoActionPerformed(evt);
            }
        });
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 120, -1));

        textContraseña.setText("Contraseña");
        getContentPane().add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        textRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textRegistro.setText("Registro");
        getContentPane().add(textRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        contraseña.setText("123");
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 120, -1));

        contraseña2.setText("123");
        contraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseña2ActionPerformed(evt);
            }
        });
        getContentPane().add(contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 120, -1));

        textContraseña2.setText("Confirmar Contraseña");
        getContentPane().add(textContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        textEstrato.setText("estrato (1-6)");
        getContentPane().add(textEstrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        estrato.setText("1");
        estrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estratoActionPerformed(evt);
            }
        });
        getContentPane().add(estrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 120, -1));

        imagenLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edificioColorFondo.png"))); // NOI18N
        imagenLateral.setText("jLabel2");
        getContentPane().add(imagenLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false); //hacemos invisible el menu actual
        MenuUsuario back = new MenuUsuario();
        back.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        
        if(contraseña.getText().equals(contraseña2.getText())){
        //creamos un objeto Usuario con todos los datos que hemos obtenido en el JFrame y ese objeto lo añadimos a nuestro arraylist de objetos
            GestionInmuebleUdc.listaUsuarios.add(new Usuario(usser.getText(),cedula.getText(), Integer.parseInt(edad.getText()), sexo.getText(), foto.getText(),contraseña.getText(),Integer.parseInt(estrato.getText()),0));
            this.setVisible(false);
            
            //informamos al usuario que su cuenta fue creada con exito
            JOptionPane.showMessageDialog(null,"Cuenta Creada con Exito!! :)","Registro Exitoso",JOptionPane.INFORMATION_MESSAGE);
            
            //ya creada la cuenta nos devolvemos al menu anterior
            MenuUsuario back = new MenuUsuario();
            back.setVisible(true);
            
        }  else {
            JOptionPane.showMessageDialog(null,"Contraseñas NO coinciden :/","Registro Fallido",JOptionPane.INFORMATION_MESSAGE);
            //y ahora nos devolvemos al menu anterior
            MenuUsuario back = new MenuUsuario();
            back.setVisible(true);
        }  
    }//GEN-LAST:event_confirmarActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void fotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fotoActionPerformed

    private void contraseña2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseña2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseña2ActionPerformed

    private void estratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField cedula;
    private javax.swing.JButton confirmar;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JPasswordField contraseña2;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField estrato;
    private javax.swing.JButton exit;
    private javax.swing.JTextField foto;
    private javax.swing.JLabel imagenLateral;
    private javax.swing.JTextField sexo;
    private javax.swing.JLabel textCedula;
    private javax.swing.JLabel textContraseña;
    private javax.swing.JLabel textContraseña2;
    private javax.swing.JLabel textEdad;
    private javax.swing.JLabel textEstrato;
    private javax.swing.JLabel textFoto;
    private javax.swing.JLabel textRegistro;
    private javax.swing.JLabel textSexo;
    private javax.swing.JLabel textUsser;
    private javax.swing.JTextField usser;
    // End of variables declaration//GEN-END:variables
}
