 
package interfaces;

public class MenuEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form MenuEmpresa
     */
    public MenuEmpresa() {
        initComponents();
        this.setLocationRelativeTo(null); //con esta linea centramos la interfaz para que aparezca centrada al usuario
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jButtonEdificio = new javax.swing.JButton();
        jButtonLocal = new javax.swing.JButton();
        jButtonPiso = new javax.swing.JButton();
        jButtonFinca = new javax.swing.JButton();
        jLabelTituloInmobiliaria = new javax.swing.JLabel();
        jLabelDeseaAgregar = new javax.swing.JLabel();
        jLabelGerenteMensaje1 = new javax.swing.JLabel();
        jLabelGerenteMensaje2 = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 0, -1, -1));

        jButtonEdificio.setText("Edificio");
        jButtonEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdificioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        jButtonLocal.setText("Local");
        getContentPane().add(jButtonLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        jButtonPiso.setText("Piso");
        jButtonPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPisoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        jButtonFinca.setText("Finca");
        getContentPane().add(jButtonFinca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        jLabelTituloInmobiliaria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTituloInmobiliaria.setText("¡Inmobiliaria UdC!");
        getContentPane().add(jLabelTituloInmobiliaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 25, -1, -1));

        jLabelDeseaAgregar.setText("Desea Agregar a Nuestra Empresa");
        getContentPane().add(jLabelDeseaAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 368, -1, -1));

        jLabelGerenteMensaje1.setText("Como nuestro gerente de confianza");
        getContentPane().add(jLabelGerenteMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 56, -1, -1));

        jLabelGerenteMensaje2.setText(" le ofrecemos una calida bienvenida");
        getContentPane().add(jLabelGerenteMensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 78, -1, -1));

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User.png"))); // NOI18N
        jLabelImagen.setText(" ");
        getContentPane().add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 100, -1, -1));

        jLabel1.setText("O quizas...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        jButton1.setText("Ver lista de inmuebles disponibles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0); //con esta linea nos salimos del programa al pulsar exit
    }//GEN-LAST:event_ExitActionPerformed

    private void jButtonEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdificioActionPerformed
        // TODO add your handling code here:
        AgregarEdificio edificio = new AgregarEdificio(); //creamos un objeto de edificio para el menu
        edificio.setVisible(true); //abrimos una ventana del JFrame 
        
        setVisible(false); //cerramos la ventana anterior, es decir la de MenuEmpresa
    }//GEN-LAST:event_jButtonEdificioActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        MenuIngreso sc = new MenuIngreso();
        sc.setVisible(true); //aca cambiamos un valor del JFrame que lo hace invisible, para hacerlo visible ponemos true
        //creamos otro objeto para abrir nuevamente el JFrame del Menu de ingreso como si estuvieramos volviendo
        this.setVisible(false); //con esto ocultamos el JFrame del Menu Empresa
    }//GEN-LAST:event_BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        ListaDisponible is = new ListaDisponible();
        
        is.setVisible(true); //hacemos visible el nuevo menu
        
        this.setVisible(false); //ocultamos el anterior
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPisoActionPerformed
        // TODO add your handling code here:
        
        AgregarPiso pisoMenu = new AgregarPiso();
        pisoMenu.setVisible(true); //mostramos la nueva interfaz
        this.setVisible(false); //ocultamos esta
    }//GEN-LAST:event_jButtonPisoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEdificio;
    private javax.swing.JButton jButtonFinca;
    private javax.swing.JButton jButtonLocal;
    private javax.swing.JButton jButtonPiso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDeseaAgregar;
    private javax.swing.JLabel jLabelGerenteMensaje1;
    private javax.swing.JLabel jLabelGerenteMensaje2;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelTituloInmobiliaria;
    // End of variables declaration//GEN-END:variables
}
